version: 0.2

env:
  variables:
    FUNCTION_NAME: "cicd-demo"
    ZIP_FILE: "lambda.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Install extra packages"
      - yum install -y zip
  build:
    commands:
      - echo "preparing zip archive"
      - zip -r $ZIP_FILE .
      - echo "Deploying lambda function"
      - aws lambda update-function-code --function-name ${FUNCTION_NAME} --zip-file fileb://${ZIP_FILE}

